{% set name = "lightkurve" %}
{% set version = "1.0.1" %}
{% set sha256 = "86a129f62b89c5271ed313115273ce8bcdabeada46e0d9449a1ded54796b9a7e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python  
    - pip
    - pytest-runner
    - astropy >=1.3
    - astroquery >=0.3.9
    - beautifulsoup4
    - matplotlib >=1.5.3
    - numpy >=1.11
    - oktopus
    - pandas
    - bokeh >=1.0
    - requests
    - scipy >=0.19.0
    - tqdm
    - scikit-learn
    - pybind11
    - celerite
  run:
    - python
    - astropy >=1.3
    - astroquery >=0.3.9
    - beautifulsoup4
    - matplotlib >=1.5.3
    - numpy >=1.11
    - oktopus
    - pandas
    - bokeh >=1.0
    - requests
    - scipy >=0.19.0
    - tqdm
    - scikit-learn
    - pybind11
    - celerite
test:
  imports:
    - lightkurve

about:
  home: https://docs.lightkurve.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A friendly package for Kepler & TESS time series analysis in Python.'

  description: |
    Lightkurve is a community-developed, open-source Python package which offers 
    a beautiful and user-friendly way to analyze astronomical flux time series data, 
    in particular the pixels and lightcurves obtained by NASA's Kepler and TESS exoplanet missions.
  doc_url: https://docs.lightkurve.org
  dev_url: https://github.com/KeplerGO/lightkurve

extra:
  recipe-maintainers:
    - gully
    - pkgw
