{% set name = "lightkurve" %}
{% set version = "1.0.0" %}
{% set sha256 = "c5f040313cad987cc00a3c617ff57a0178d989a4d076fa3bde0a53c2508ab9f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - astropy
    - astroquery
    - beautifulsoup4
    - matplotlib
    - numpy >=1.10  # required by autograd via oktopus
    - oktopus
    - pandas
    - bokeh >=1.0 # required for .interact() as of 1.0b23
    - pip
    - pytest-runner
    - python
    - requests
    - scipy
    - tqdm
    - scikit-learn
    - pybind11
    - celerite
  run:
    - astropy
    - astroquery
    - beautifulsoup4
    - matplotlib
    - {{ pin_compatible('numpy') }}
    - oktopus
    - bokeh
    - pandas
    - python
    - requests
    - scipy
    - tqdm
    - scikit-learn
    - pybind11
    - celerite
test:
  imports:
    - lightkurve

about:
  home: https://docs.lightkurve.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A beautiful package for astronomical flux time series analysis in Python'

  description: |
    The lightkurve Python package offers a beautiful and user-friendly way to
    analyze astronomical flux time series data, in particular the pixels and
    lightcurves obtained by NASA’s Kepler, K2, and TESS missions.
  doc_url: https://docs.lightkurve.org
  dev_url: https://github.com/KeplerGO/lightkurve

extra:
  recipe-maintainers:
    - gully
    - pkgw
