{% set name = "lightkurve" %}
{% set version = "2.0.8" %}
{% set sha256 = "5d7d8b99d1d2c9ebd64a6de46af3ba8eb303df5fb8969daff54e3d608e5bd523" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - poetry
    - poetry-core
    - pip
    - pytest-runner

    - astropy >=4.1
    - astroquery >=0.3.10
    - beautifulsoup4 >=4.6.0
    - bokeh >=1.0
    - fbpca >=1.0
    - matplotlib-base >=1.5.3
    - memoization >=0.3.1
    - numpy >=1.11
    - oktopus >=0.1.2
    - pandas >=1.1.4
    - patsy >=0.5.1
    - requests >=2.22.0
    - scikit-learn >=0.24.0
    - scipy >=0.19.0
    - tqdm >=4.25.0
    - uncertainties >=3.1.4
  run:
    - python >=3.6

    - astropy >=4.1
    - astroquery >=0.3.10
    - beautifulsoup4 >=4.6.0
    - bokeh >=1.0
    - fbpca >=1.0
    - matplotlib-base >=1.5.3
    - memoization >=0.3.1
    - numpy >=1.11
    - oktopus >=0.1.2
    - pandas >=1.1.4
    - patsy >=0.5.1
    - requests >=2.22.0
    - scikit-learn >=0.24.0
    - scipy >=0.19.0
    - tqdm >=4.25.0
    - uncertainties >=3.1.4
test:
  imports:
    - lightkurve

about:
  home: https://docs.lightkurve.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A friendly package for Kepler & TESS time series analysis in Python.

  description: |
    Lightkurve is a community-developed, open-source Python package which offers
    a beautiful and user-friendly way to analyze astronomical flux time series data,
    in particular the pixels and lightcurves obtained by NASA's Kepler and TESS exoplanet missions.
  doc_url: https://docs.lightkurve.org
  dev_url: https://github.com/lightkurve/lightkurve

extra:
  recipe-maintainers:
    - gully
    - pkgw
    - barentsen
