travis:
  secure:
    BINSTAR_TOKEN: GY662wsGbXWRjUQ8wDMIhuG9kxXdu0+5ySMLdssKUqxFuMHwy7Eaw/d6s1I89ix8Glk1JNRMsrx0AefuU+Wb4tQd2InpxtCYoTVEL9YX2ba11P7ZSdoy7L5tit57WmS/fVRP2izOROI4T4NUp+wcggWsdUNOX5ruM5vYVWjzaa9riTX2iWXmkmWiEM2mYmPmVqOBpQwZBgQPhHy2HJ71et7QnwgC7RnRM5sS8LIRtWh4JOQ9uiVKMk5IxGwE076kgiMWe283uvaaC0w/WaK/ldAcY1eJKzGrnBRKvfPJuSUgVfIF8giujeA+DetCjUssF/Q0WiWPDvInnHYndjA4hVOX2CxShEq5dUHeABdyb2fJ6s/S+x2zPqzbqWNkig54PD5IkLbfkC1cz3asXenYl8MN3t4H5tmrIqKoBnVowabBq7tDY4gExku2odJthUDrjNubzmHzMPdeKpqacODdY6T39WKJwaDn2+Tpc9SD5B+jltFzs1yEf5apTKUo5k8IKs22CTiBnI8JWy/Gs+hKlcYmftI6Uw76tzBCl1tFoieoynU02BCmBGH9U0Vh6+lC/j1dsRhVO27SDl0DBD/RlALKF2fc0SEG6qssh8EwZyJcvlE5KxCSeWmaq8Hmxi2fCXVVX5dZ6XJVredqTioHFv95DY+gbw8OskMM/wCGS34=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
